// File generated by the Locomotive SiteBuilder CLI. DO NOT MODIFY IT!

'use strict';

const Rendering = require('locomotive-site-builder-rendering');
const port      = process.env.PORT || 3333;

require('babel-register');

const definitions = require('./app/themes/definitions');
const routes      = require('./app/themes/routes');

Rendering.local.startServer(port, __dirname, definitions.default, routes.default);
