// File generated by the Locomotive SiteBuilder CLI. DO NOT MODIFY IT!

'use strict';

const Rendering = require('locomotive-site-builder-rendering');

require('babel-register');

const definitions = require('./app/themes/definitions');

Rendering.local.runTests(__dirname, definitions.default);
