// File generated by the Locomotive SiteBuilder CLI. DO NOT MODIFY IT!

import block_header from "./blocks/header";
import layout from "./layout";


export default {
	blocks: {
		header: block_header
	},
	layout: layout
}
// done